### ISSUE TITLE
index.py中的bug

### ISSUE THREAD

**Issue by tyu-t** [themanforfree/HAUT-checkin#1]
在[index.py](https://github.com/themanforfree/HAUT-checkin/blob/master/index.py)的第31行写错了，应该是`uid = error[i][3]`。

而且`device_seed`没有写上，不写的话后面一直用的是上一个循环的最后一个人的设备码。

```python
            phone = error[i][0]
            password = error[i][1]
            uid = error[i][2]
```

**Comment by themanforfree** [comment]
感谢
代码是在旧版本的基础上改动的
error这一部分碰到的概率不大
修改代码后调试没有发现这个错误
