### ISSUE TITLE
sms收不到短信吖大佬

### ISSUE THREAD

**Issue by shipors** [themanforfree/HAUT-checkin#5]
换了手机也没作用，应该换个手机号试试吗，触发时微信显示获取token失败

**Comment by themanforfree** [comment]
sms.py验证过你的手机号和device_seed以后才可以触发

**Comment by shipors** [comment]
> sms.py验证过你的手机号和device_seed以后才可以触发

就是在这一步，输入了用户名和device_seed，显示短信发送成功但是收不到短信

**Comment by shipors** [comment]
![QQ截图20210302100637](https://user-images.githubusercontent.com/56157328/109585762-0d3a1b00-7b3f-11eb-85e2-3b0caaa457a1.png)

**Comment by themanforfree** [comment]
我没遇到过这个问题
你换个手机号或者等明天再试试吧
还不行的话就留个联系方式
回头有空我再帮你看看

**Comment by themanforfree** [comment]
username是你的手机号

**Comment by shipors** [comment]
已解决，多谢大佬
